-- Per-effort declared impacts (JSON array of TaskImpact rows).
-- Populated by `complete_task` (and friends) when the agent
-- declares the wiki pages / tasks / commits / findings / files
-- a given effort touched. Projected into `page_ref` under the
-- `impact` ref_type so cross-page backlinks see them.
--
-- JSON shape:
--   [{"kind":"wiki","id":"some-slug","action":"created"},
--    {"kind":"task","id":"42","action":"completed"},
--    ...]
ALTER TABLE task_effort ADD COLUMN impacts_json TEXT;
